version: '3.8'

services:
  app:
    build: .
    container_name: wd_block_driver_notificator

    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Kiev

    restart: always
